"""GitLab MR에 리뷰 결과를 코멘트로 작성한다."""

import os

import httpx

GITLAB_URL = os.environ.get("CI_SERVER_URL", "https://gitlab.com")
PRIVATE_TOKEN = os.environ.get("GITLAB_TOKEN", "")

SEVERITY_EMOJI = {
    "critical": "\u2757",  # ❗
    "high": "\U0001f534",  # 🔴
    "medium": "\U0001f7e1",  # 🟡
    "low": "\U0001f7e2",  # 🟢
}


def _headers() -> dict:
    return {"PRIVATE-TOKEN": PRIVATE_TOKEN}


def _format_comment(issue: dict) -> str:
    emoji = SEVERITY_EMOJI.get(issue.get("severity", "low"), "")
    issue_type = issue.get("type", "review").upper()
    message = issue.get("message", "")
    suggestion = issue.get("suggestion", "")

    body = f"{emoji} **[{issue_type}]** {message}"
    if suggestion:
        body += f"\n\n**수정 제안:**\n```suggestion\n{suggestion}\n```"

    return body


def _build_summary(issues: list[dict]) -> str:
    """전체 리뷰 요약 본문을 만든다."""
    if not issues:
        return "## AI Code Review\n\n이슈가 발견되지 않았습니다. :tada:"

    count_by_severity = {}
    for issue in issues:
        sev = issue.get("severity", "low")
        count_by_severity[sev] = count_by_severity.get(sev, 0) + 1

    lines = ["## AI Code Review Summary\n"]
    for sev in ("critical", "high", "medium", "low"):
        count = count_by_severity.get(sev, 0)
        if count:
            emoji = SEVERITY_EMOJI.get(sev, "")
            lines.append(f"- {emoji} **{sev.upper()}**: {count}건")

    lines.append(f"\n총 **{len(issues)}건**의 이슈가 발견되었습니다.\n")
    lines.append("---\n*Generated by AI PR Review Agent*")

    return "\n".join(lines)


async def post_mr_note(project_id: str, mr_iid: str, body: str) -> None:
    """MR에 일반 노트(코멘트)를 작성한다."""
    url = f"{GITLAB_URL}/api/v4/projects/{project_id}/merge_requests/{mr_iid}/notes"

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(url, headers=_headers(), json={"body": body})
        resp.raise_for_status()


async def post_inline_comment(
    project_id: str,
    mr_iid: str,
    filename: str,
    line: int,
    body: str,
    sha: str,
) -> None:
    """MR diff의 특정 라인에 인라인 코멘트를 작성한다."""
    url = (
        f"{GITLAB_URL}/api/v4/projects/{project_id}"
        f"/merge_requests/{mr_iid}/discussions"
    )
    payload = {
        "body": body,
        "position": {
            "base_sha": sha,
            "head_sha": sha,
            "start_sha": sha,
            "position_type": "text",
            "new_path": filename,
            "new_line": line,
        },
    }

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(url, headers=_headers(), json=payload)
        # 인라인 코멘트 실패 시 무시 (라인 매핑이 안 되는 경우)
        if resp.status_code >= 400:
            return


async def post_review(
    project_id: str, mr_iid: str, issues: list[dict], sha: str
) -> None:
    """리뷰 결과를 MR에 게시한다 (요약 + 인라인 코멘트)."""
    # 1) 인라인 코멘트
    for issue in issues:
        line = issue.get("line")
        filename = issue.get("filename")
        if line and filename:
            body = _format_comment(issue)
            await post_inline_comment(
                project_id, mr_iid, filename, line, body, sha
            )

    # 2) 전체 요약 노트
    summary = _build_summary(issues)
    await post_mr_note(project_id, mr_iid, summary)
