"""GitHub PR 또는 커밋에 리뷰 결과를 코멘트로 작성한다."""

import logging

import httpx

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"

SEVERITY_EMOJI = {
    "critical": "\u2757",  # ❗
    "high": "\U0001f534",  # 🔴
    "medium": "\U0001f7e1",  # 🟡
    "low": "\U0001f7e2",  # 🟢
}


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
    }


def _format_comment(issue: dict) -> str:
    emoji = SEVERITY_EMOJI.get(issue.get("severity", "low"), "")
    issue_type = issue.get("type", "review").upper()
    message = issue.get("message", "")
    suggestion = issue.get("suggestion", "")

    body = f"{emoji} **[{issue_type}]** {message}"
    if suggestion:
        body += f"\n\n**수정 제안:**\n```suggestion\n{suggestion}\n```"

    return body


def _build_summary(issues: list[dict]) -> str:
    """전체 리뷰 요약 본문을 만든다."""
    if not issues:
        return "## AI Code Review\n\n이슈가 발견되지 않았습니다. :tada:"

    count_by_severity = {}
    for issue in issues:
        sev = issue.get("severity", "low")
        count_by_severity[sev] = count_by_severity.get(sev, 0) + 1

    lines = ["## AI Code Review Summary\n"]
    for sev in ("critical", "high", "medium", "low"):
        count = count_by_severity.get(sev, 0)
        if count:
            emoji = SEVERITY_EMOJI.get(sev, "")
            lines.append(f"- {emoji} **{sev.upper()}**: {count}건")

    lines.append(f"\n총 **{len(issues)}건**의 이슈가 발견되었습니다.\n")
    lines.append("---\n*Generated by AI PR Review Agent*")

    return "\n".join(lines)


async def post_pr_review(
    owner: str,
    repo: str,
    pr_number: int,
    commit_sha: str,
    issues: list[dict],
    token: str,
) -> None:
    """PR에 Review API로 인라인 코멘트 + 요약을 한 번에 제출한다."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/reviews"

    comments = []
    for issue in issues:
        line = issue.get("line")
        filename = issue.get("filename")
        if line and filename:
            comments.append(
                {
                    "path": filename,
                    "line": line,
                    "side": "RIGHT",
                    "body": _format_comment(issue),
                }
            )

    summary = _build_summary(issues)
    payload = {
        "commit_id": commit_sha,
        "event": "COMMENT",
        "body": summary,
        "comments": comments,
    }

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(url, headers=_headers(token), json=payload)
        if resp.status_code >= 400:
            logger.error(f"PR 리뷰 실패 ({resp.status_code}): {resp.text}")
            if comments:
                payload["comments"] = []
                resp = await client.post(url, headers=_headers(token), json=payload)
                if resp.status_code >= 400:
                    logger.error(f"PR 요약 재시도 실패 ({resp.status_code}): {resp.text}")


async def post_commit_comment(
    owner: str,
    repo: str,
    commit_sha: str,
    issues: list[dict],
    token: str,
) -> None:
    """커밋에 인라인 코멘트 + 요약을 작성한다."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/commits/{commit_sha}/comments"

    async with httpx.AsyncClient(timeout=30) as client:
        for issue in issues:
            line = issue.get("line")
            filename = issue.get("filename")
            if line and filename:
                payload = {
                    "body": _format_comment(issue),
                    "path": filename,
                    "line": line,
                }
                resp = await client.post(
                    url, headers=_headers(token), json=payload
                )
                if resp.status_code >= 400:
                    logger.warning(f"인라인 코멘트 실패 ({filename}:{line}): {resp.status_code}")
                    continue

        summary = _build_summary(issues)
        resp = await client.post(url, headers=_headers(token), json={"body": summary})
        if resp.status_code >= 400:
            logger.error(f"커밋 요약 코멘트 실패 ({resp.status_code}): {resp.text}")
